<?php

/**
 * @file
 * Contains header_top_links.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function header_top_links_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the header_top_links module.
    case 'help.page.header_top_links':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Header Top Links') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function header_top_links_theme() {
  return [
    'header_top_links' => [
      'variables' => [
        'user_name' => NULL
      ],
    ],
  ];
}
